import React from 'react';
import { Card } from '../ui/Card';
import { Button } from '../ui/Button';
import { CheckCircle2, FileText, Clock, Euro, Download, ArrowRight } from 'lucide-react';
import { cn } from '../../lib/utils';
// @ts-ignore
import { jsPDF } from "jspdf";
import { useLanguage } from '../../lib/LanguageContext';

type DocStatus = 'ready' | 'warning' | 'pending';

const REQUIRED_DOCS: { name: string; status: DocStatus; note: string }[] = [
  { name: 'Pasaporte Completo', status: 'ready', note: 'Recibido' },
  { name: 'Antecedentes Penales', status: 'warning', note: 'Apostilla' },
  { name: 'Contrato de Trabajo', status: 'pending', note: 'Pendiente' },
  { name: 'Informe de Insercion Social', status: 'pending', note: 'Pendiente' },
  { name: 'Empadronamiento Historico', status: 'warning', note: 'Actualizar' },
  { name: 'Oferta Laboral Sellada', status: 'pending', note: 'Falta firma' },
  { name: 'Medios Economicos', status: 'pending', note: 'Adjuntar' },
  { name: 'Fotografias DNI', status: 'ready', note: 'OK' }
];

export const EvaluationResult: React.FC = () => {
  const { t } = useLanguage();

  const handleContact = () => {
    const subject = encodeURIComponent("Consulta sobre Arraigo Social - Ref #EM-2024-8821");
    window.location.href = `mailto:citas@emigrai360.com?subject=${subject}`;
  };

  const handleDownload = () => {
    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const marginX = 20;
      const marginY = 20;
      const contentWidth = pageWidth - marginX * 2;

      // Header
      doc.setFillColor(11, 47, 79);
      doc.rect(0, 0, pageWidth, 35, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(22);
      doc.text("emigrAI", marginX, 23);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(12);
      doc.text("Informe de Viabilidad / Viability Report", pageWidth - marginX, 23, { align: "right" } as any);

      // Basic info
      let cursorY = marginY + 30;
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(10);
      doc.text(`Fecha: ${new Date().toLocaleDateString()}`, marginX, cursorY);
      doc.text("Referencia: #EM-2024-8821", pageWidth - marginX, cursorY, { align: "right" } as any);

      // Result title
      cursorY += 20;
      doc.setFontSize(16);
      doc.setFont("helvetica", "bold");
      doc.text("Resultado / Result", marginX, cursorY);

      // Score box
      cursorY += 10;
      doc.setFillColor(240, 253, 244);
      doc.setDrawColor(22, 163, 74);
      doc.roundedRect(marginX, cursorY, contentWidth, 32, 3, 3, 'FD');
      doc.setTextColor(22, 101, 52);
      doc.setFontSize(14);
      doc.text("VIABILIDAD ALTA / HIGH VIABILITY (87%)", marginX + 10, cursorY + 20);

      // Details
      cursorY += 50;
      doc.setFont("helvetica", "bold");
      doc.setTextColor(0, 0, 0);
      doc.text("Detalles / Details:", marginX, cursorY);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      const detailLines = [
        "- 3-4 Months / Meses",
        "- Cost: 800 EUR - 1.2k EUR",
        `- Docs: ${REQUIRED_DOCS.length}`
      ];
      detailLines.forEach((line, idx) => {
        doc.text(line, marginX + 10, cursorY + 10 + idx * 8);
      });

      // Documents
      cursorY += 40;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.text("Documentos requeridos / Required documents:", marginX, cursorY);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      let docY = cursorY + 8;
      REQUIRED_DOCS.forEach((docItem) => {
        if (docY > pageHeight - marginY - 20) {
          doc.addPage();
          docY = marginY;
        }
        const statusLabel = docItem.status === 'ready' ? 'Completado' : docItem.note;
        doc.text(`- ${docItem.name} (${statusLabel})`, marginX, docY);
        docY += 6;
      });

      const pendingDocs = REQUIRED_DOCS.filter(d => d.status !== 'ready');
      if (pendingDocs.length) {
        docY += 4;
        if (docY > pageHeight - marginY - 20) {
          doc.addPage();
          docY = marginY;
        }
        doc.setFont("helvetica", "bold");
        doc.text("Documentos pendientes / Missing documents:", marginX, docY);
        doc.setFont("helvetica", "normal");
        docY += 6;
        pendingDocs.forEach((docItem) => {
          if (docY > pageHeight - marginY - 20) {
            doc.addPage();
            docY = marginY;
          }
          doc.text(`- ${docItem.name} (${docItem.note})`, marginX, docY);
          docY += 6;
        });
      }

      // Disclaimer
      doc.setFontSize(9);
      doc.setTextColor(128, 128, 128);
      doc.text("Generated by AI / Generado por IA.", marginX, pageHeight - marginY);

      doc.save("emigrai360-report.pdf");
    } catch (error) {
      console.error("Error generating PDF", error);
      alert("Error generating PDF");
    }
  };

  return (
    <Card className="w-full max-w-4xl mx-auto overflow-hidden animate-fade-in border-0 shadow-2xl">
      <div className="bg-success-gradient p-1 h-2 w-full" />

      <div className="grid md:grid-cols-3 gap-0">
        <div className="md:col-span-1 bg-gray-50 p-8 flex flex-col items-center justify-center border-b md:border-b-0 md:border-r border-gray-100">
          <div className="relative w-40 h-40 flex items-center justify-center">
            <div className="absolute inset-0 rounded-full border-[10px] border-gray-200"></div>
            <div
              className="absolute inset-0 rounded-full border-[10px] border-accent border-l-transparent border-b-transparent transform -rotate-45 transition-all duration-1000"
              style={{ clipPath: 'polygon(0 0, 100% 0, 100% 100%, 0% 100%)' }}
            ></div>
            <div className="text-center z-10">
              <span className="text-4xl font-bold text-gray-800">87%</span>
              <p className="text-xs text-gray-500 uppercase font-semibold mt-1">{t('res_viability')}</p>
            </div>
          </div>

          <div className="mt-6 text-center">
            <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-green-100 text-green-700 text-sm font-bold">
              <CheckCircle2 size={14} /> {t('res_probability_high')}
            </span>
            <p className="text-sm text-gray-500 mt-2 px-2">
              {t('res_match')}
            </p>
          </div>
        </div>

        <div className="md:col-span-2 p-8">
          <div className="flex justify-between items-start mb-6">
            <div>
              <h2 className="text-2xl font-bold text-gray-900">Arraigo Social</h2>
              <p className="text-text-secondary">{t('res_recommended')}</p>
            </div>
            <div className="text-right hidden sm:block">
              <p className="text-xs text-gray-400">Referencia</p>
              <p className="font-mono text-sm">#EM-2024-8821</p>
            </div>
          </div>

          <div className="grid grid-cols-3 gap-4 mb-8">
            <div className="p-3 bg-blue-50 rounded-lg">
              <div className="flex items-center gap-2 text-primary mb-1">
                <Clock size={16} />
                <span className="text-xs font-bold uppercase">{t('res_time')}</span>
              </div>
              <p className="font-semibold text-gray-900">3-4 Meses</p>
            </div>
            <div className="p-3 bg-purple-50 rounded-lg">
              <div className="flex items-center gap-2 text-secondary mb-1">
                <Euro size={16} />
                <span className="text-xs font-bold uppercase">{t('res_cost')}</span>
              </div>
              <p className="font-semibold text-gray-900">800 EUR - 1.2k EUR</p>
            </div>
            <div className="p-3 bg-orange-50 rounded-lg">
              <div className="flex items-center gap-2 text-orange-600 mb-1">
                <FileText size={16} />
                <span className="text-xs font-bold uppercase">{t('res_docs')}</span>
              </div>
              <p className="font-semibold text-gray-900">{REQUIRED_DOCS.length} {t('res_docs_req')}</p>
            </div>
          </div>

          <div className="space-y-4">
            <h4 className="font-semibold text-sm text-gray-900 uppercase tracking-wide">{t('res_crit_docs')}</h4>
            <div className="space-y-2">
              {REQUIRED_DOCS.map((doc, i) => (
                <div key={doc.name + i} className="flex items-center justify-between p-3 border rounded-md bg-white hover:bg-gray-50 transition">
                  <div className="flex items-center gap-3">
                    <FileText size={18} className="text-gray-400" />
                    <span className="text-sm font-medium text-gray-700">{doc.name}</span>
                  </div>
                  <span
                    className={cn(
                      "text-xs px-2 py-0.5 rounded-full font-medium",
                      doc.status === 'ready'
                        ? "bg-green-100 text-green-700"
                        : doc.status === 'warning'
                        ? "bg-yellow-100 text-yellow-700"
                        : "bg-gray-100 text-gray-600"
                    )}
                  >
                    {doc.note}
                  </span>
                </div>
              ))}
            </div>
          </div>

          <div className="mt-8 flex flex-col sm:flex-row gap-3">
            <Button className="flex-1 w-full" size="lg" onClick={handleContact}>
              {t('btn_contact')} <ArrowRight size={18} className="ml-2 shrink-0" />
            </Button>
            <Button variant="outline" size="lg" className="w-full sm:w-auto" onClick={handleDownload}>
              <Download size={18} className="mr-2 shrink-0" /> {t('btn_pdf')}
            </Button>
          </div>
        </div>
      </div>
    </Card>
  );
};
