import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'es' | 'en' | 'fr' | 'ar' | 'ro' | 'zh' | 'pt' | 'bg' | 'uk';

export const LANGUAGES: { code: Language; name: string; flag: string }[] = [
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦' },
  { code: 'ro', name: 'Română', flag: '🇷🇴' },
  { code: 'zh', name: '中文', flag: '🇨🇳' },
  { code: 'pt', name: 'Português', flag: '🇵🇹' },
  { code: 'bg', name: 'Български', flag: '🇧🇬' },
  { code: 'uk', name: 'Українська', flag: '🇺🇦' },
];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    nav_evaluator: "Evaluador IA",
    nav_management: "Gestión",
    nav_professional: "Area Profesional",
    hero_title: "Evalúa tu caso migratorio con IA",
    hero_subtitle: "Nuestro asistente inteligente analiza tu perfil en tiempo real para recomendarte la mejor vía de regularización en España.",
    chat_initial: "👋 ¡Hola! Soy EmigraBot. Estoy aquí para evaluar la viabilidad de tu caso. ¿Cuál es tu nacionalidad?",
    chat_placeholder: "Escribe tu respuesta...",
    chat_typing: "Escribiendo...",
    chat_error: "Error de conexión.",
    chat_analyzing: "Analizando perfil...",
    voice_start: "Hablar",
    voice_end: "Terminar",
    voice_listening: "Escuchando...",
    voice_speaking: "Hablando...",
    voice_connecting: "Conectando...",
    voice_error: "Error voz",
    res_viability: "Viabilidad",
    res_probability_high: "ALTA PROBABILIDAD",
    res_match: "Tu perfil encaja con los requisitos.",
    res_recommended: "Trámite recomendado por IA",
    res_time: "Tiempo",
    res_cost: "Coste Aprox.",
    res_docs: "Documentos",
    res_docs_req: "Requeridos",
    res_crit_docs: "Documentación Crítica",
    btn_contact: "Contactar Gestoría",
    btn_pdf: "Informe PDF",
    dash_title: "Panel de Gestión",
    dash_new: "+ Nuevo Caso",
    dash_active: "Activos",
    dash_approved: "Aprobados",
    dash_pending: "Pendientes",
    dash_success_rate: "Éxito",
    footer: "© 2024 EMIGRAI 360. Todos los derechos reservados.",
    login_title: "Acceso Profesional",
    login_desc: "Portal para abogados y gestores colegiados.",
    login_email: "Correo Corporativo",
    login_pass: "Contraseña",
    login_btn: "Entrar al Portal",
    login_forgot: "¿Olvidaste tu contraseña?",
  },
  en: {
    nav_evaluator: "AI Evaluator",
    nav_management: "Management",
    nav_professional: "Pro Area",
    hero_title: "Evaluate your immigration case with AI",
    hero_subtitle: "Our intelligent assistant analyzes your profile in real-time to recommend the best regularization path in Spain.",
    chat_initial: "👋 Hi! I'm EmigraBot. I'm here to evaluate your case viability. What is your nationality?",
    chat_placeholder: "Type here...",
    chat_typing: "Typing...",
    chat_error: "Connection error.",
    chat_analyzing: "Analyzing profile...",
    voice_start: "Speak",
    voice_end: "End Call",
    voice_listening: "Listening...",
    voice_speaking: "Speaking...",
    voice_connecting: "Connecting...",
    voice_error: "Voice error",
    res_viability: "Viability",
    res_probability_high: "HIGH PROBABILITY",
    res_match: "Your profile matches requirements.",
    res_recommended: "AI Recommended Process",
    res_time: "Time",
    res_cost: "Est. Cost",
    res_docs: "Documents",
    res_docs_req: "Required",
    res_crit_docs: "Critical Docs",
    btn_contact: "Contact Agency",
    btn_pdf: "PDF Report",
    dash_title: "Management Dashboard",
    dash_new: "+ New Case",
    dash_active: "Active",
    dash_approved: "Approved",
    dash_pending: "Pending",
    dash_success_rate: "Success Rate",
    footer: "© 2024 EMIGRAI 360. All rights reserved.",
    login_title: "Professional Access",
    login_desc: "Portal for lawyers and registered consultants.",
    login_email: "Corporate Email",
    login_pass: "Password",
    login_btn: "Enter Portal",
    login_forgot: "Forgot password?",
  },
  fr: {
    nav_evaluator: "Évaluateur IA",
    nav_management: "Gestion",
    nav_professional: "Espace Pro",
    hero_title: "Évaluez votre cas d'immigration avec l'IA",
    hero_subtitle: "Notre assistant intelligent analyse votre profil en temps réel pour recommander la meilleure voie de régularisation en Espagne.",
    chat_initial: "👋 Bonjour ! Je suis EmigraBot. Je suis ici pour évaluer la viabilité de votre cas. Quelle est votre nationalité ?",
    chat_placeholder: "Écrivez votre réponse...",
    chat_typing: "En train d'écrire...",
    chat_error: "Erreur de connexion.",
    chat_analyzing: "Analyse du profil...",
    voice_start: "Parler",
    voice_end: "Terminer",
    voice_listening: "Écoute...",
    voice_speaking: "Parle...",
    voice_connecting: "Connexion...",
    voice_error: "Erreur vocale",
    res_viability: "Viabilité",
    res_probability_high: "HAUTE PROBABILITÉ",
    res_match: "Votre profil correspond aux exigences.",
    res_recommended: "Processus Recommandé par IA",
    res_time: "Temps",
    res_cost: "Coût Est.",
    res_docs: "Documents",
    res_docs_req: "Requis",
    res_crit_docs: "Documentation Critique",
    btn_contact: "Contacter l'Agence",
    btn_pdf: "Rapport PDF",
    dash_title: "Tableau de Bord",
    dash_new: "+ Nouveau Cas",
    dash_active: "Actifs",
    dash_approved: "Approuvés",
    dash_pending: "En Attente",
    dash_success_rate: "Succès",
    footer: "© 2024 EMIGRAI 360. Tous droits réservés.",
    login_title: "Accès Professionnel",
    login_desc: "Portail pour avocats et consultants.",
    login_email: "Email Pro",
    login_pass: "Mot de passe",
    login_btn: "Entrer",
    login_forgot: "Mot de passe oublié ?",
  },
  ar: {
    nav_evaluator: "مقيم الذكاء الاصطناعي",
    nav_management: "إدارة",
    nav_professional: "منطقة مهنية",
    hero_title: "قيم حالة الهجرة الخاصة بك مع الذكاء الاصطناعي",
    hero_subtitle: "يقوم مساعدنا الذكي بتحليل ملفك الشخصي في الوقت الفعلي للتوصية بأفضل مسار للتسوية في إسبانيا.",
    chat_initial: "👋 مرحبًا! أنا EmigraBot. أنا هنا لتقييم جدوى حالتك. ما هي جنسيتك؟",
    chat_placeholder: "أكتب إجابتك...",
    chat_typing: "يكتب...",
    chat_error: "خطأ في الاتصال.",
    chat_analyzing: "تحليل الملف الشخصي...",
    voice_start: "تحدث",
    voice_end: "إنهاء",
    voice_listening: "استماع...",
    voice_speaking: "يتحدث...",
    voice_connecting: "جاري الاتصال...",
    voice_error: "خطأ صوتي",
    res_viability: "الجدوى",
    res_probability_high: "احتمالية عالية",
    res_match: "ملفك الشخصي يطابق المتطلبات.",
    res_recommended: "الإجراء الموصى به",
    res_time: "الوقت",
    res_cost: "التكلفة التقديرية",
    res_docs: "وثائق",
    res_docs_req: "مطلوب",
    res_crit_docs: "وثائق حاسمة",
    btn_contact: "اتصل بالوكالة",
    btn_pdf: "تقرير PDF",
    dash_title: "لوحة القيادة",
    dash_new: "+ حالة جديدة",
    dash_active: "نشط",
    dash_approved: "موافق عليه",
    dash_pending: "قيد الانتظار",
    dash_success_rate: "نسبة النجاح",
    footer: "© 2024 EMIGRAI 360. جميع الحقوق محفوظة.",
    login_title: "الوصول المهني",
    login_desc: "بوابة المحامين والاستشاريين.",
    login_email: "البريد الإلكتروني",
    login_pass: "كلمة المرور",
    login_btn: "دخول",
    login_forgot: "هل نسيت كلمة المرور؟",
  },
  ro: {
    nav_evaluator: "Evaluator IA",
    nav_management: "Gestiune",
    nav_professional: "Zona Pro",
    hero_title: "Evaluează cazul tău de imigrare cu IA",
    hero_subtitle: "Asistentul nostru inteligent îți analizează profilul în timp real pentru a recomanda cea mai bună cale de regularizare în Spania.",
    chat_initial: "👋 Bună! Sunt EmigraBot. Sunt aici să evaluez viabilitatea cazului tău. Care este naționalitatea ta?",
    chat_placeholder: "Scrie răspunsul...",
    chat_typing: "Scrie...",
    chat_error: "Eroare de conexiune.",
    chat_analyzing: "Analizare profil...",
    voice_start: "Vorbește",
    voice_end: "Termină",
    voice_listening: "Ascult...",
    voice_speaking: "Vorbesc...",
    voice_connecting: "Se conectează...",
    voice_error: "Eroare voce",
    res_viability: "Viabilitate",
    res_probability_high: "PROBABILITATE RIDICATĂ",
    res_match: "Profilul tău se potrivește cerințelor.",
    res_recommended: "Proces Recomandat de IA",
    res_time: "Timp",
    res_cost: "Cost Est.",
    res_docs: "Documente",
    res_docs_req: "Necesare",
    res_crit_docs: "Documentație Critică",
    btn_contact: "Contactează Agenția",
    btn_pdf: "Raport PDF",
    dash_title: "Panou de Control",
    dash_new: "+ Caz Nou",
    dash_active: "Active",
    dash_approved: "Aprobate",
    dash_pending: "În Așteptare",
    dash_success_rate: "Succes",
    footer: "© 2024 EMIGRAI 360. Toate drepturile rezervate.",
    login_title: "Acces Profesional",
    login_desc: "Portal pentru avocați și consultanți.",
    login_email: "Email Corporativ",
    login_pass: "Parolă",
    login_btn: "Intră în Portal",
    login_forgot: "Ai uitat parola?",
  },
  zh: {
    nav_evaluator: "AI 评估员",
    nav_management: "管理",
    nav_professional: "专业领域",
    hero_title: "用 AI 评估您的移民案例",
    hero_subtitle: "我们的智能助手实时分析您的个人资料，为您推荐在西班牙的最佳合法化途径。",
    chat_initial: "👋 您好！我是 EmigraBot。我在这里评估您的案例可行性。您的国籍是什么？",
    chat_placeholder: "输入您的回答...",
    chat_typing: "正在输入...",
    chat_error: "连接错误。",
    chat_analyzing: "分析个人资料...",
    voice_start: "说话",
    voice_end: "结束",
    voice_listening: "正在听...",
    voice_speaking: "正在说...",
    voice_connecting: "正在连接...",
    voice_error: "语音错误",
    res_viability: "可行性",
    res_probability_high: "高概率",
    res_match: "您的个人资料符合要求。",
    res_recommended: "AI 推荐流程",
    res_time: "时间",
    res_cost: "预估费用",
    res_docs: "文件",
    res_docs_req: "必需",
    res_crit_docs: "关键文件",
    btn_contact: "联系机构",
    btn_pdf: "PDF 报告",
    dash_title: "管理仪表板",
    dash_new: "+ 新案例",
    dash_active: "活跃",
    dash_approved: "已批准",
    dash_pending: "待处理",
    dash_success_rate: "成功率",
    footer: "© 2024 EMIGRAI 360. 保留所有权利。",
    login_title: "专业访问",
    login_desc: "律师和顾问门户。",
    login_email: "企业邮箱",
    login_pass: "密码",
    login_btn: "进入门户",
    login_forgot: "忘记密码？",
  },
  pt: {
    nav_evaluator: "Avaliador IA",
    nav_management: "Gestão",
    nav_professional: "Área Pro",
    hero_title: "Avalie o seu caso de imigração com IA",
    hero_subtitle: "O nosso assistente inteligente analisa o seu perfil em tempo real para recomendar o melhor caminho de regularização em Espanha.",
    chat_initial: "👋 Olá! Sou o EmigraBot. Estou aqui para avaliar a viabilidade do seu caso. Qual é a sua nacionalidade?",
    chat_placeholder: "Escreva a sua resposta...",
    chat_typing: "A escrever...",
    chat_error: "Erro de conexão.",
    chat_analyzing: "A analisar perfil...",
    voice_start: "Falar",
    voice_end: "Terminar",
    voice_listening: "A ouvir...",
    voice_speaking: "A falar...",
    voice_connecting: "A ligar...",
    voice_error: "Erro de voz",
    res_viability: "Viabilidade",
    res_probability_high: "ALTA PROBABILIDADE",
    res_match: "O seu perfil corresponde aos requisitos.",
    res_recommended: "Processo Recomendado por IA",
    res_time: "Tempo",
    res_cost: "Custo Est.",
    res_docs: "Documentos",
    res_docs_req: "Necessários",
    res_crit_docs: "Documentação Crítica",
    btn_contact: "Contactar Agência",
    btn_pdf: "Relatório PDF",
    dash_title: "Painel de Gestão",
    dash_new: "+ Novo Caso",
    dash_active: "Ativos",
    dash_approved: "Aprovados",
    dash_pending: "Pendentes",
    dash_success_rate: "Sucesso",
    footer: "© 2024 EMIGRAI 360. Todos os direitos reservados.",
    login_title: "Acesso Profissional",
    login_desc: "Portal para advogados e consultores.",
    login_email: "Email Corporativo",
    login_pass: "Palavra-passe",
    login_btn: "Entrar",
    login_forgot: "Esqueceu-se da palavra-passe?",
  },
  bg: {
    nav_evaluator: "AI Оценител",
    nav_management: "Управление",
    nav_professional: "Професионална зона",
    hero_title: "Оценете имиграционния си случай с AI",
    hero_subtitle: "Нашият интелигентен асистент анализира профила ви в реално време, за да препоръча най-добрия път за легализация в Испания.",
    chat_initial: "👋 Здравейте! Аз съм EmigraBot. Тук съм, за да оценя жизнеспособността на вашия случай. Каква е вашата националност?",
    chat_placeholder: "Напишете отговора си...",
    chat_typing: "Пише...",
    chat_error: "Грешка при свързване.",
    chat_analyzing: "Анализиране на профила...",
    voice_start: "Говори",
    voice_end: "Край",
    voice_listening: "Слушам...",
    voice_speaking: "Говоря...",
    voice_connecting: "Свързване...",
    voice_error: "Грешка глас",
    res_viability: "Жизнеспособност",
    res_probability_high: "ВИСОКА ВЕРОЯТНОСТ",
    res_match: "Профилът ви отговаря на изискванията.",
    res_recommended: "Препоръчан процес от AI",
    res_time: "Време",
    res_cost: "Прогн. Разходи",
    res_docs: "Документи",
    res_docs_req: "Необходими",
    res_crit_docs: "Критична документация",
    btn_contact: "Свържете се с агенция",
    btn_pdf: "PDF Доклад",
    dash_title: "Табло за управление",
    dash_new: "+ Нов случай",
    dash_active: "Активни",
    dash_approved: "Одобрени",
    dash_pending: "Чакащи",
    dash_success_rate: "Успех",
    footer: "© 2024 EMIGRAI 360. Всички права запазени.",
    login_title: "Професионален достъп",
    login_desc: "Портал за адвокати и консултанти.",
    login_email: "Служебен имейл",
    login_pass: "Парола",
    login_btn: "Вход",
    login_forgot: "Забравена парола?",
  },
  uk: {
    nav_evaluator: "AI Оцінювач",
    nav_management: "Управління",
    nav_professional: "Професійна зона",
    hero_title: "Оцініть свою імміграційну справу за допомогою AI",
    hero_subtitle: "Наш інтелектуальний помічник аналізує ваш профіль у режимі реального часу, щоб рекомендувати найкращий шлях легалізації в Іспанії.",
    chat_initial: "👋 Привіт! Я EmigraBot. Я тут, щоб оцінити життєздатність вашої справи. Яка ваша національність?",
    chat_placeholder: "Напишіть свою відповідь...",
    chat_typing: "Друкує...",
    chat_error: "Помилка з'єднання.",
    chat_analyzing: "Аналіз профілю...",
    voice_start: "Говорити",
    voice_end: "Кінець",
    voice_listening: "Слухаю...",
    voice_speaking: "Говорю...",
    voice_connecting: "З'єднання...",
    voice_error: "Помилка голосу",
    res_viability: "Життєздатність",
    res_probability_high: "ВИСОКА ЙМОВІРНІСТЬ",
    res_match: "Ваш профіль відповідає вимогам.",
    res_recommended: "Рекомендований процес AI",
    res_time: "Час",
    res_cost: "Орієнт. Вартість",
    res_docs: "Документи",
    res_docs_req: "Потрібні",
    res_crit_docs: "Критична документація",
    btn_contact: "Зв'язатися з агентством",
    btn_pdf: "Звіт PDF",
    dash_title: "Панель управління",
    dash_new: "+ Нова справа",
    dash_active: "Активні",
    dash_approved: "Затверджені",
    dash_pending: "В очікуванні",
    dash_success_rate: "Успіх",
    footer: "© 2024 EMIGRAI 360. Всі права захищені.",
    login_title: "Професійний доступ",
    login_desc: "Портал для юристів та консультантів.",
    login_email: "Корпоративна пошта",
    login_pass: "Пароль",
    login_btn: "Увійти",
    login_forgot: "Забули пароль?",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('es');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
